services:
  bereal_database:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5535:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  glados_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - .env
    depends_on:
      - bereal_database
    restart: always
